### ISSUE TITLE
Refactor ParseJson into multiple classes

### ISSUE THREAD

**Issue by audreyseo** [cmu-mars/ros1-to-ros2-sandbox#23]
There's a lot of stuff happening in the main function in ParseJson that isn't related to parsing json files at all, so I just want to split that up a little bit more.

This would also include making this more modular so that we can choose any sketch for parsing.

**Comment by ivoysey** [comment]
It also seems like it's throwing some exceptions? In the latest.log there are things like this

```
17:17:22.802 WARN  [main] petri.MethodsToPetriNet        (MethodsToPetriNet.java:508) - Caught exception in MethodsToPetriNet.addFlowToPetri:
uniol.apt.adt.exception.FlowExistsException: Arc with sourceId 'const std::string&' and targetId 'rclcpp::Node::Node2' already exists in graph ''
	at uniol.apt.adt.pn.PetriNet.createFlow(PetriNet.java:188) ~[apt.jar:?]
	at uniol.apt.adt.pn.PetriNet.createFlow(PetriNet.java:218) ~[apt.jar:?]
	at uniol.apt.adt.pn.PetriNet.createFlow(PetriNet.java:235) ~[apt.jar:?]
	at ros2sy.petri.MethodsToPetriNet.addFlowToPetri(MethodsToPetriNet.java:506) [ros2sy.jar:?]
	at ros2sy.petri.MethodsToPetriNet.addArgFlowsToPetri(MethodsToPetriNet.java:480) [ros2sy.jar:?]
	at ros2sy.petri.MethodsToPetriNet.addTransitionFlowToPetri(MethodsToPetriNet.java:557) [ros2sy.jar:?]
	at ros2sy.petri.MethodsToPetriNet.convert(MethodsToPetriNet.java:345) [ros2sy.jar:?]
	at ros2sy.petri.MethodsToPetriNet.<init>(MethodsToPetriNet.java:71) [ros2
```
I don't know if those are meaningful or can be ignored, but it would be good to know which case you're in. And maybe spend the time to add some careful try-catches to squelch the errors -- but that can be a real rabbit hole, and if you write ones that are too general you can hide actual problems, so it might not be worth the effort.
